name: build site

on:
  push:
    branches:
      - main

permissions:
  contents: [read, write]

jobs:
  check-links:
    runs-on: ubuntu-latest
    steps:
      - name: set up node
        with:
          node-version: 16

      - name: run script
        run: cd src && node build.js

      - name: commit changes
        uses: EndBug/add-and-commit@v9 # You can change this to use a specific version.
        with:
          add: docs
          default_author: github_actions
          message: compile

